### ISSUE TITLE
built-in function symbols can not find

### ISSUE THREAD

**Issue by huahuaLover** [tamarin-prover/homebrew-tap#30]
I apologize for asking you some questions about Tamarin here, but I currently don't have a better way and I hope you can understand.

I found KDF function and SndS(~cid,A,B,m) fact in ccs18-5G\5G-AKA-bindingChannel\5G_AKA.spthy when I was studying it. However, I couldn't find any relevant description in the Tamarin manual. I would like to know how to access information about functions or facts that are not documented in the Tamarin manual. Looking forward to your response
Currently, I am learning how to use Tamarin through the Tamarin manual. Could you provide me with some suggestions to help me better master it?

I want to model and optimize 5G AKA using Tamarin. Currently, I am looking at the file "ccs18-5G\5G-AKA-bindingChannel\5G_AKA.spthy". I would greatly appreciate it if you could provide me with some advice. 

I am looking forward to your replay

**Comment by jdreier** [comment]
This is not a bug report.

**Comment by huahuaLover** [comment]
Could you tell me how to contact Ralf Sasse or could you pass on my question to him? I urgently need his help. Thank you very much.

**Comment by rsasse** [comment]
As Jannik has posted in the prior issue, Tamarin issues are the wrong place for this! Please send mail to the mailing list already posted by Jannik there:

https://groups.google.com/group/tamarin-prover

and also realize that we are all busy with our actual jobs, and not waiting to respond to questions immediately all the time. You may eventually get a response there.

In general, you can find the information specific to models in the accompanying paper, or general information in the manual. That is sufficient, and there is no further information needed.

**Comment by huahuaLover** [comment]
I am delighted to receive your email. I previously received your patient response on GitHub, so I wanted to reach out to you again. I apologize for any inconvenience caused. I am a fourth-year undergraduate student and it is my first time exploring formal analysis. I am particularly interested in formal protocol analysis and currently studying Tamarin. Whenever I encounter difficulties and do not know how to solve them, I thought of contacting you. I apologize for bothering you again! Wishing you smooth work and a joyful life!
